spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/poetry?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #配置访问的路径
server:
  servlet:
    context-path: /admin
#  mybatis.configuration.mapUnderscoreToCamelCase=true